### ISSUE TITLE
Add 'Tape Gateway' to the Storage Gateway solutions list

### ISSUE THREAD

**Issue by devcexx** [SkullTech/aws-solutions-architect-associate-notes#2]
As appears in the official documentation (https://docs.aws.amazon.com/storagegateway/latest/userguide/WhatIsStorageGateway.html), AWS offers a tape-based storage gateway. It should be mentioned on the list of services of the section of the Storage Gateway to prevent confusion.

**Comment by skulltech** [comment]
Thanks for pointing that out!! I'll definitely add that. Cheers!
